version: '3.9'

services:
  postgres:
    image: postgres
    hostname: postgres
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8

  redis:
    image: redis
    hostname: redis
    ports:
      - '6379:6379'

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DATABASE_URL=postgresql://test:test@postgres:5432/test?schema=public
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SESSION_SECRET="secret"
      - BCRYPT_ROUNDS=10
    depends_on:
      - postgres
      - redis
    ports:
      - '8080:8080'
    command: pnpm start:migrate:prod
    volumes:
      - /app/node_modules
